name: deploy-online-endpoint-pipeline

on: 
  repository_dispatch:
    types: [batch_pipeline_completed]

jobs:
  get-config:
    uses: Azure/mlops-templates/.github/workflows/read-yaml.yml@main
    with:
      file_name: config-infra-prod.yml
  create-endpoint:
    needs: get-config
    uses: ./.github/workflows/create-endpoint.yml
    with:
      resource_group: ${{ needs.get-config.outputs.resource_group }}
      workspace_name: ${{ needs.get-config.outputs.aml_workspace }} 
      endpoint_file: mlops/azureml/deploy/online/online-endpoint.yml
      endpoint_name: ${{ format('{0}-gha-{1}', needs.get-config.outputs.deployment_name, needs.get-config.outputs.oep) }}
      endpoint_type: online
    secrets:
      creds: ${{secrets.AZURE_CREDENTIALS}}
  create-deployment:
    uses: ./.github/workflows/create-deployment.yml
    needs: [get-config,create-endpoint]
    with:
      resource_group: ${{ needs.get-config.outputs.resource_group }}
      workspace_name: ${{ needs.get-config.outputs.aml_workspace }} 
      endpoint_file: mlops/azureml/deploy/online/online-deployment.yml
      endpoint_name: ${{ format('{0}-gha-{1}', needs.get-config.outputs.deployment_name, needs.get-config.outputs.oep) }}
      endpoint_type: online
      deployment_name: ${{ format('{0}-online-dp', needs.get-config.outputs.deployment_name) }}
    secrets:
      creds: ${{secrets.AZURE_CREDENTIALS}}
  allocate-traffic:
    uses: Azure/mlops-templates/.github/workflows/allocate-traffic.yml@main
    needs: [get-config,create-deployment]
    with:
      resource_group: ${{ needs.get-config.outputs.resource_group }}
      workspace_name: ${{ needs.get-config.outputs.aml_workspace }} 
      traffic_allocation: ${{ format('{0}-online-dp=100', needs.get-config.outputs.deployment_name) }}
      endpoint_name: ${{ format('{0}-gha-{1}', needs.get-config.outputs.deployment_name, needs.get-config.outputs.oep) }}
    secrets:
      creds: ${{secrets.AZURE_CREDENTIALS}}