name: model-training-pipeline # test3

on: 
  push:
    paths:
      - '.github/workflows/deploy-model-training-pipeline.yml'
      - 'data-science/src/**'
      - 'mlops/azureml/train/**'
      - 'data/**'

jobs:
  get-config:
      uses: ./.github/workflows/read-yaml.yml
      with:
        file_name: config-infra-prod.yml
  register-environment:
      needs: get-config
      uses: ./.github/workflows/register-environment.yml
      with:
        resource_group: ${{ needs.get-config.outputs.resource_group }}
        workspace_name: ${{ needs.get-config.outputs.aml_workspace }}
        deployment_name: ${{ needs.get-config.outputs.deployment_name }}     
        environment_file:  mlops/azureml/train/train-env.yml
        conda_file: data-science/environment/train-conda.yml
      secrets:
          creds: ${{secrets.AZURE_CREDENTIALS}}
          
  register-dataset:
    needs: get-config
    uses: ./.github/workflows/register-dataset.yml
    with:
      resource_group: ${{ needs.get-config.outputs.resource_group }}
      workspace_name: ${{ needs.get-config.outputs.aml_workspace }}
      deployment_name: ${{ needs.get-config.outputs.deployment_name }}
      name: taxi-data
      data_file: mlops/azureml/train/data.yml
    secrets:
      creds: ${{secrets.AZURE_CREDENTIALS}}
      
  create-compute:
      needs: [get-config,register-environment,register-dataset]
      uses: ./.github/workflows/create-compute.yml
      with:
        cluster_name: cpu-cluster
        size: Standard_D2_v2
        min_instances: 0
        max_instances: 4
        cluster_tier: dedicated
        resource_group: ${{ needs.get-config.outputs.resource_group }}
        workspace_name: ${{ needs.get-config.outputs.aml_workspace }}
        deployment_name: ${{ needs.get-config.outputs.deployment_name }}     
      secrets:
          creds: ${{secrets.AZURE_CREDENTIALS}}